#include "field.hpp"
void arr(const vector<E>&a){cout<<"[";for(int i=0;i<(int)a.size();i++){if(i)cout<<",";cout<<a[i];}cout<<"]";}
void mat(const vector<vector<E>>&a){cout<<"[";for(int i=0;i<(int)a.size();i++){if(i)cout<<",";arr(a[i]);}cout<<"]";}
int main(){init();vector<vector<E>>p(8,vector<E>(12)),K(12,vector<E>(192)),Qp(28,vector<E>(79));for(auto*o:{&p,&K,&Qp})for(auto&r:*o)for(auto&x:r)cin>>x;vector<E>alpha(12),beta(12),tau(12),cs(8),ds(8);for(int i=0;i<8;i++)cs[i]=p[i][2];for(int a=0;a<12;a++){beta[a]=K[a][85];alpha[a]=mul(sub(K[a][1],beta[a]),inv(cs[0]));} // i7 coefficient1 is85
vector<vector<E>>res(8,vector<E>(12));int di=-1,pivot=-1;for(int i=0;i<8;i++)for(int a=0;a<12;a++){res[i][a]=sub(sub(K[a][12*i+1],beta[a]),mul(cs[i],alpha[a]));if(res[i][a]&&di<0){di=i;pivot=a;}}assert(di>=0);tau=res[di];for(int i=0;i<8;i++){ds[i]=mul(res[i][pivot],inv(tau[pivot]));for(int a=0;a<12;a++)assert(res[i][a]==mul(ds[i],tau[a]));}
vector<vector<E>>map(7,vector<E>(12));for(int s=0;s<6;s++)for(int a=0;a<12;a++)map[s][a]=add(K[a][138+s],mul(2,alpha[a]));map[6]=tau;auto R=map;for(int i=0;i<7;i++){R[i].resize(19);R[i][12+i]=1;}vector<int>piv;int rank=0;for(int k=0;k<12;k++){int at=rank;while(at<7&&!R[at][k])at++;if(at==7)continue;swap(R[at],R[rank]);E iv=inv(R[rank][k]);for(int j=k;j<19;j++)R[rank][j]=mul(R[rank][j],iv);for(int i=0;i<7;i++)if(i!=rank&&R[i][k]){E cf=R[i][k];for(int j=k;j<19;j++)R[i][j]=sub(R[i][j],mul(cf,R[rank][j]));}piv.push_back(k);rank++;}assert(rank==7);vector<vector<E>>lift(7,vector<E>(12)),ker;for(int i=0;i<7;i++)for(int j=0;j<7;j++)lift[j][piv[i]]=R[i][12+j];set<int>ps(piv.begin(),piv.end());for(int f=0;f<12;f++)if(!ps.count(f)){vector<E>v(12);v[f]=1;for(int i=0;i<7;i++)v[piv[i]]=neg(R[i][f]);ker.push_back(v);}auto evaluate=[&](const vector<E>&v){vector<E>out(28);for(int r=0;r<28;r++){int k=0;for(int a=0;a<12;a++)for(int b=a;b<12;b++)out[r]=add(out[r],mul(Qp[r][k++],mul(v[a],v[b])));}return out;};vector<vector<E>>reduced(28,vector<E>(28));int k=0;for(int a=0;a<7;a++)for(int b=a;b<7;b++){auto val=evaluate(lift[a]);if(a!=b){auto vb=evaluate(lift[b]);vector<E>sum(12);for(int i=0;i<12;i++)sum[i]=add(lift[a][i],lift[b][i]);auto vs=evaluate(sum);for(int r=0;r<28;r++)val[r]=sub(sub(vs[r],val[r]),vb[r]);}for(int r=0;r<28;r++)reduced[r][k]=val[r];k++;}
for(auto&v:ker){auto q=evaluate(v);for(E z:q)assert(!z);for(int a=0;a<12;a++){vector<E>u(12);u[a]=1;auto qu=evaluate(u);u[a]=add(u[a],v[a]);for(int b=0;b<12;b++)if(b!=a)u[b]=v[b];auto sum=evaluate(u);for(int r=0;r<28;r++)assert(sum[r]==qu[r]);}}
auto rr=reduced;vector<vector<E>> transform(28,vector<E>(28));for(int i=0;i<28;i++)transform[i][i]=1;int rk=0;for(int c=0;c<28;c++){int at=rk;while(at<28&&!rr[at][c])at++;if(at==28)continue;swap(rr[at],rr[rk]);swap(transform[at],transform[rk]);E iv=inv(rr[rk][c]);for(int j=c;j<28;j++)rr[rk][j]=mul(rr[rk][j],iv);for(int j=0;j<28;j++)transform[rk][j]=mul(transform[rk][j],iv);for(int i=0;i<28;i++)if(i!=rk&&rr[i][c]){E cf=rr[i][c];for(int j=c;j<28;j++)rr[i][j]=sub(rr[i][j],mul(cf,rr[rk][j]));for(int j=0;j<28;j++)transform[i][j]=sub(transform[i][j],mul(cf,transform[rk][j]));}rk++;}rr.resize(rk);transform.resize(rk);bool base=true;for(auto&r:rr)for(E x:r)if(x>=729)base=false;cout<<"{\"active_rank\":7,\"invisible_dimension\":5,\"quadratic_rank\":"<<rk<<",\"coefficients_in_F729\":"<<(base?"true":"false")<<",\"leading_coefficients\":";arr(cs);cout<<",\"slope_direction\":";arr(ds);cout<<",\"active_map\":";mat(map);cout<<",\"active_lifts\":";mat(lift);cout<<",\"invisible_kernel\":";mat(ker);cout<<",\"reduced_tensor\":";mat(reduced);cout<<",\"rref_equations\":";mat(rr);cout<<",\"row_combinations\":";mat(transform);cout<<"}\n";
}
