#include "field.hpp"
E ev(const vector<E>&p,E x){E v=0;for(int k=p.size()-1;k>=0;k--)v=add(mul(v,x),p[k]);return v;}
E der(const vector<E>&p,E x,int order){E v=0;for(int k=p.size()-1;k>=order;k--){int bin=1;for(int j=1;j<=order;j++)bin=bin*(k-j+1)/j;v=add(mul(v,x),mul(bin%3,p[k]));}return v;}
void arr(const vector<E>&v){cout<<"[";for(int i=0;i<(int)v.size();i++){if(i)cout<<",";cout<<v[i];}cout<<"]";}
void mat(const vector<vector<E>>&a){cout<<"[";for(int i=0;i<(int)a.size();i++){if(i)cout<<",";arr(a[i]);}cout<<"]";}
int main(){init();E z=3,eta=add(add(z,power(z,2)),power(z,4)),eb=sub(2,eta),alpha=mul(eb,inv(eta));vector<vector<E>>p(8,vector<E>(12));for(int i=0;i<7;i++){E a=mul(eta,power(z,2*i)),b=power(z,3*i),c=power(z,4*i);p[i][2]=mul(eb,power(z,5*i));p[i][3]=neg(c);p[i][4]=b;p[i][5]=sub(c,a);p[i][6]=b;p[i][8]=b;p[i][11]=a;}
map<E,E>as;for(E u=0;u<B;u++)as.emplace(sub(power(u,3),u),u);assert(as.size()==243);vector<E>nodes,words,defect;vector<vector<int>>masks;set<E>seen;int counts[8]={};
for(int orbit=0;orbit<2;orbit++)for(int t=0;t<7;t++){E base=mul(orbit?alpha:1,power(z,t)),root=0;bool found=false;for(int c=0;c<3;c++){auto it=as.find(sub(base,mul(c,z)));if(it!=as.end()){root=add(it->second,mul(c,B));found=true;break;}}assert(found);for(int e=0;e<3;e++){E x=add(root,e),xx=mul(x,x);assert(x&&seen.insert(x).second&&sub(power(x,3),x)==base);E w=orbit?0:mul(xx,power(z,5*t));vector<int>ids;for(int i=0;i<8;i++){E val=0;if(i<7){E v=mul(power(z,(7-i)%7),base);val=mul(xx,mul(power(z,5*i),add(add(mul(eta,power(v,3)),mul(v,v)),add(v,eb))));}assert(val==ev(p[i],x));if(val==w){ids.push_back(i);counts[i]++;}}assert(ids.size()==4);nodes.push_back(x);words.push_back(w);defect.push_back(orbit?mul(eta,mul(xx,power(z,5*t))):0);masks.push_back(ids);}}
for(int j=0;j<3;j++)for(int b=0;b<2;b++){vector<int>ids;for(int i=0;i<8;i++)if((i>>j&1)==b){ids.push_back(i);counts[i]++;}nodes.push_back(0);words.push_back(0);defect.push_back(0);masks.push_back(ids);}for(int c:counts)assert(c==24);
const int N=192,W=385;vector<vector<E>>a(N,vector<E>(W));vector<E>rhs(N);int row=0;vector<pair<int,int>>inc;
for(int j=0;j<48;j++)for(int i:masks[j]){E xp=1;for(int k=0;k<12;k++){a[row][12*i+k]=xp;xp=mul(xp,nodes[j]);}a[row][96+j]=der(p[i],nodes[j],1);a[row][144+j]=2;rhs[row]=i==7?defect[j]:0;a[row][N]=rhs[row];a[row][N+1+row]=1;inc.emplace_back(i,j);row++;}assert(row==N);auto original=a;vector<int>piv,pr,ids(N);for(int i=0;i<N;i++)ids[i]=i;int rank=0;for(int k=0;k<N;k++){int r=rank;while(r<N&&!a[r][k])r++;if(r==N)continue;swap(a[r],a[rank]);swap(ids[r],ids[rank]);pr.push_back(ids[rank]);E iv=inv(a[rank][k]);for(int c=k;c<W;c++)a[rank][c]=mul(a[rank][c],iv);for(int j=0;j<N;j++)if(j!=rank&&a[j][k]){E cf=a[j][k];for(int c=k;c<W;c++)a[j][c]=sub(a[j][c],mul(cf,a[rank][c]));}piv.push_back(k);rank++;}
int bad=-1;for(int j=rank;j<N;j++)if(a[j][N]){bad=j;break;}vector<vector<E>>kernels,left;set<int>ps(piv.begin(),piv.end());for(int f=0;f<N;f++)if(!ps.count(f)){vector<E>v(N);v[f]=1;for(int j=0;j<rank;j++)v[piv[j]]=neg(a[j][f]);kernels.push_back(v);}for(int j=rank;j<N;j++){vector<E>v(N);for(int k=0;k<N;k++)v[k]=a[j][N+1+k];left.push_back(v);}vector<E>obs(N),part(N),split(N);if(bad>=0)for(int j=0;j<N;j++)obs[j]=a[bad][N+1+j];else for(int j=0;j<rank;j++)part[piv[j]]=a[j][N];for(int j=0;j<6;j++)split[138+j]=j;
for(auto&v:kernels)for(int r=0;r<N;r++){E s=0;for(int k=0;k<N;k++)s=add(s,mul(original[r][k],v[k]));assert(!s);}for(int r=0;r<N;r++){E s=0;for(int k=0;k<N;k++)s=add(s,mul(original[r][k],split[k]));assert(!s);}if(bad>=0){E v=0;for(int r=0;r<N;r++){v=add(v,mul(obs[r],rhs[r]));}assert(v);for(int k=0;k<N;k++){E s=0;for(int r=0;r<N;r++)s=add(s,mul(obs[r],original[r][k]));assert(!s);}}

vector<vector<E>>ech(N);int br=0;auto insert=[&](vector<E>v){for(int k=0;k<N;k++)if(v[k]){if(!ech[k].empty()){E cf=v[k];for(int j=k;j<N;j++)v[j]=sub(v[j],mul(cf,ech[k][j]));}else{E iv=inv(v[k]);for(int j=k;j<N;j++)v[j]=mul(v[j],iv);ech[k]=v;br++;return true;}}return false;};auto check=[&](const vector<E>&v){for(int r=0;r<N;r++){E sum=0;for(int k=0;k<N;k++)sum=add(sum,mul(original[r][k],v[k]));assert(!sum);}};
vector<vector<E>>gauges;for(int k=0;k<12;k++){vector<E>v(N);for(int i=0;i<8;i++)v[12*i+k]=1;for(int j=0;j<48;j++)v[144+j]=power(nodes[j],k);gauges.push_back(v);} {vector<E>v(N);for(int i=0;i<8;i++)for(int k=0;k<12;k++)v[12*i+k]=p[i][k];for(int j=0;j<48;j++)v[144+j]=words[j];gauges.push_back(v);}for(int typ=0;typ<3;typ++){vector<E>v(N);for(int i=0;i<8;i++)for(int k=0;k<12;k++){if(typ==0&&k)v[12*i+k-1]=neg(mul(k%3,p[i][k]));if(typ==1)v[12*i+k]=neg(mul(k%3,p[i][k]));if(typ==2&&k<11)v[12*i+k+1]=mul((11-k)%3,p[i][k]);}for(int j=0;j<48;j++){v[96+j]=power(nodes[j],typ);if(typ==2)v[144+j]=mul(2,mul(nodes[j],words[j]));}gauges.push_back(v);}for(auto&v:gauges){check(v);assert(insert(v));}assert(br==16);vector<vector<E>>comp;for(auto&v:kernels)if(insert(v))comp.push_back(v);assert(comp.size()==12&&br==28);
vector<pair<int,int>>mons;for(int a=0;a<12;a++)for(int b=a;b<12;b++)mons.emplace_back(a,b);vector<vector<E>>quad(N,vector<E>(78));for(int r=0;r<N;r++){auto[i,j]=inc[r];E x=nodes[j],h2=der(p[i],x,2),xi[12],rd[12];for(int a=0;a<12;a++){xi[a]=comp[a][96+j];vector<E>v(12);for(int k=0;k<12;k++)v[k]=comp[a][12*i+k];rd[a]=der(v,x,1);}for(int k=0;k<78;k++){auto[a,b]=mons[k];E val=mul(h2,mul(xi[a],xi[b]));if(a==b)val=add(val,mul(rd[a],xi[a]));else val=add(mul(2,val),add(mul(rd[a],xi[b]),mul(rd[b],xi[a])));quad[r][k]=val;}}
vector<vector<E>>proj(28,vector<E>(79));for(int a=0;a<28;a++)for(int r=0;r<N;r++)if(left[a][r]){for(int k=0;k<78;k++)proj[a][k]=add(proj[a][k],mul(left[a][r],quad[r][k]));proj[a][78]=add(proj[a][78],mul(left[a][r],rhs[r]));}
auto qr=proj;for(int a=0;a<28;a++){qr[a].resize(107);qr[a][79+a]=1;}int qrank=0;vector<int>qpiv;for(int k=0;k<78;k++){int r=qrank;while(r<28&&!qr[r][k])r++;if(r==28)continue;swap(qr[r],qr[qrank]);E iv=inv(qr[qrank][k]);for(int c=k;c<107;c++)qr[qrank][c]=mul(qr[qrank][c],iv);for(int a=0;a<28;a++)if(a!=qrank&&qr[a][k]){E cf=qr[a][k];for(int c=k;c<107;c++)qr[a][c]=sub(qr[a][c],mul(cf,qr[qrank][c]));}qpiv.push_back(k);qrank++;}int qbad=-1;for(int a=qrank;a<28;a++)if(qr[a][78]){qbad=a;break;}vector<E>qleft(28);if(qbad>=0)for(int a=0;a<28;a++)qleft[a]=qr[qbad][79+a];cerr<<"quadratic rank "<<qrank<<" monomial consistent "<<(qbad<0)<<"\n";
cout<<"{\"rank\":"<<rank<<",\"nullity\":"<<N-rank<<",\"mod9_consistent\":"<<(bad<0?"true":"false")<<",\"nodes\":";arr(nodes);cout<<",\"words\":";arr(words);cout<<",\"masks\":[";for(int j=0;j<48;j++){if(j)cout<<",";vector<E>v;for(int i:masks[j])v.push_back(i);arr(v);}cout<<"],\"polynomials\":";mat(p);cout<<",\"rhs\":";arr(rhs);cout<<",\"pivot_rows\":[";for(int i=0;i<rank;i++){if(i)cout<<",";cout<<pr[i];}cout<<"],\"pivot_columns\":[";for(int i=0;i<rank;i++){if(i)cout<<",";cout<<piv[i];}cout<<"],\"kernel_basis\":";mat(kernels);cout<<",\"left_kernel_basis\":";mat(left);cout<<",\"mod9_obstruction\":";arr(obs);cout<<",\"particular\":";arr(part);cout<<",\"distinct_node_tangent\":";arr(split);cout<<",\"kernel_complement\":";mat(comp);cout<<",\"quadratic_projection\":";mat(proj);cout<<",\"quadratic_rank\":"<<qrank<<",\"quadratic_monomial_consistent\":"<<(qbad<0?"true":"false")<<",\"quadratic_left_obstruction\":";arr(qleft);cout<<"}\n";cerr<<"rank "<<rank<<" nullity "<<N-rank<<" mod9 "<<(bad<0)<<" fresh tangent0..5 verified\n";
}
