#include <algorithm>
#include <array>
#include <cassert>
#include <fstream>
#include <iostream>
#include <set>
#include <vector>
using namespace std;int p;int mod(long long a){a%=p;return a<0?a+p:a;}int power(int a,int n){int r=1;for(;n;n>>=1,a=mod((long long)a*a))if(n&1)r=mod((long long)r*a);return r;}using Poly=vector<int>;Poly timesroot(Poly a,int y){Poly b(a.size()+1);for(int j=0;j<(int)a.size();++j){b[j]=mod(b[j]-(long long)y*a[j]);b[j+1]=mod(b[j+1]+a[j]);}return b;}int eval(const Poly&a,int x){int v=0;for(int i=(int)a.size()-1;i>=0;--i)v=mod((long long)v*x+a[i]);return v;}int rot(int s){return ((s<<1)&255)|(s>>7);}bool canonical(int s){int t=s;for(int j=1;j<8;++j){t=rot(t);if(t<s)return false;}return true;}
struct Interp{array<int,4> ys;array<Poly,4> bases;};
int main(int argc,char**argv){assert(argc>=2);p=atoi(argv[1]);assert(p%8==1);int z=2;while(power(z,8)!=1||power(z,4)==1)++z;vector<int>zs(8);zs[0]=1;for(int j=1;j<8;++j)zs[j]=mod(zs[j-1]*z);vector<int>cosets;set<int>seen;for(int x=1;x<p;++x)if(!seen.count(x)){cosets.push_back(x);for(int y:zs)seen.insert(mod(x*y));}vector<int>masks,sources;for(int s=0;s<256;++s)if(__builtin_popcount((unsigned)s)==4){masks.push_back(s);if(canonical(s))sources.push_back(s);}vector<vector<Interp>> ip(cosets.size(),vector<Interp>(70));for(int a=1;a<(int)cosets.size();++a)for(int t=0;t<70;++t){auto&v=ip[a][t];int k=0;for(int j=0;j<8;++j)if(masks[t]>>j&1)v.ys[k++]=mod(cosets[a]*zs[j]);for(int i=0;i<4;++i){Poly B{1};int den=1;for(int j=0;j<4;++j)if(j!=i){B=timesroot(B,v.ys[j]);den=mod((long long)den*(v.ys[i]-v.ys[j]));}int inv=power(den,p-2);for(int&x:B)x=mod((long long)x*inv);v.bases[i]=B;}}
 long long tested=0,hits=0;for(int h:{1,2,5,6})for(int sm:sources){Poly A{1};for(int j=0;j<8;++j)if(sm>>j&1)A=timesroot(A,zs[j]);for(int a=1;a<(int)cosets.size();++a)for(int t=0;t<70;++t){auto&I=ip[a][t];Poly Q(4),P(8);for(int i=0;i<4;++i){int v=mod((long long)power(I.ys[i],h)*power(eval(A,I.ys[i]),p-2));for(int j=0;j<4;++j)Q[j]=mod(Q[j]+(long long)v*I.bases[i][j]);}for(int i=0;i<5;++i)for(int j=0;j<4;++j)P[i+j]=mod(P[i+j]+(long long)A[i]*Q[j]);++tested;bool distinct=false;for(int j=0;j<8;++j)if(P[j]&&((j-h)&1))distinct=true;if(!distinct)continue;vector<int>selected{0,a},values{0,1},supports{sm,masks[t]};bool guards=true;for(int l=0;l<2;++l){int n=0;for(int j=0;j<8;++j){int x=mod(cosets[selected[l]]*zs[j]);if(eval(P,x)==mod((long long)values[l]*power(x,h)))++n;}if(n!=4)guards=false;}if(!guards)continue;
 for(int b=1;b<(int)cosets.size();++b)if(b!=a){vector<int>bs(p);for(int j=0;j<8;++j){int x=mod(cosets[b]*zs[j]);int v=mod((long long)eval(P,x)*power(power(x,h),p-2));bs[v]|=1<<j;}for(int v=0;v<p;++v)if(__builtin_popcount((unsigned)bs[v])==4){selected.push_back(b);values.push_back(v);supports.push_back(bs[v]);break;}if(selected.size()==4)break;}
 if(selected.size()==4){++hits;cout<<"{\"p\":"<<p<<",\"zeta\":"<<z<<",\"h\":"<<h<<",\"P\":[";for(int j=0;j<8;++j)cout<<(j?",":"")<<P[j];cout<<"],\"cosets\":[";for(int j=0;j<4;++j)cout<<(j?",":"")<<cosets[selected[j]];cout<<"],\"values\":[";for(int j=0;j<4;++j)cout<<(j?",":"")<<values[j];cout<<"],\"supports\":[";for(int j=0;j<4;++j)cout<<(j?",":"")<<supports[j];cout<<"]}"<<endl;return 0;}
 }}cerr<<"p="<<p<<" tested="<<tested<<" hits="<<hits<<" source_reps="<<sources.size()<<" cosets="<<cosets.size()<<"\n";}
