#include <vector>
#include <array>
#include <algorithm>
#include <iostream>
#include <fstream>
#include <chrono>
#include <string>
using P=std::vector<int>;int mod;
int norm(long long a){a%=mod;if(a<0)a+=mod;return a;}int inv(int a){int b=mod-2,r=1;for(;b;b>>=1,a=norm(a*a))if(b&1)r=norm(r*a);return r;}
void trim(P&a){while(!a.empty()&&!a.back())a.pop_back();}P con(int a){return a?P{norm(a)}:P{};}P add(P a,const P&b,int scale=1){a.resize(std::max(a.size(),b.size()));for(int i=0;i<(int)b.size();i++)a[i]=norm(a[i]+scale*b[i]);trim(a);return a;}P mul(const P&a,const P&b){if(a.empty()||b.empty())return{};P c(a.size()+b.size()-1);for(int i=0;i<(int)a.size();i++)for(int j=0;j<(int)b.size();j++)c[i+j]=norm(c[i+j]+a[i]*b[j]);trim(c);return c;}P sc(P a,int s){for(int&x:a)x=norm(x*s);trim(a);return a;}P rem(P a,const P&b){if(b.empty())throw 1;int v=inv(b.back());while(a.size()>=b.size()&&!a.empty()){int d=a.size()-b.size(),c=norm(a.back()*v);for(int i=0;i<(int)b.size();i++)a[i+d]=norm(a[i+d]-c*b[i]);trim(a);}return a;}P gcd(P a,P b){while(!b.empty()){P c=rem(a,b);a=b;b=c;}return a.empty()?a:sc(a,inv(a.back()));}int ev(const P&a,int x){int y=0;for(int i=(int)a.size()-1;i>=0;i--)y=norm(y*x+a[i]);return y;}
struct R{P a,b;};int ls,lh;P zz{0,1};R plus(R a,R b,int s=1){return{add(a.a,b.a,s),add(a.b,b.b,s)};}R scale(R a,int s){return{sc(a.a,s),sc(a.b,s)};}R times(R a,R b){P bd=mul(a.b,b.b);return{add(mul(a.a,b.a),mul(zz,bd),-lh),add(add(mul(a.a,b.b),mul(a.b,b.a)),bd,-ls)};}R scalar(P a){return{a,{}};}R one(){return scalar({1});}
int root(int a){for(int x=0;x<mod;x++)if(x*x%mod==a)return x;return -1;}std::vector<int> roots(int s,int p){std::vector<int>v;for(int x=0;x<mod;x++)if(norm(x*x+s*x+p)==0)v.push_back(x);return v;}
std::string arr(const P&a){std::string s="[";for(int i=0;i<(int)a.size();i++){if(i)s+=",";s+=std::to_string(a[i]);}return s+"]";}
int main(int argc,char**argv){mod=std::stoi(argv[1]);std::string path=argv[2];auto start=std::chrono::steady_clock::now();long long shapes=0,edgeok=0,leadok=0,gcdpos=0,zroots=0,split=0,hits=0,chartskip=0,algebraic=0;std::vector<std::string> algebraic_rows,gcd_rows;long long collision_hist[29]={};std::ofstream out(path);out<<"{\"p\":"<<mod<<",\"hits\":[";bool first=true;
for(int b=1;b<mod;b++)for(int c=1;c<mod;c++)for(int q=1;q<mod;q++)for(int h=0;h<mod;h++){
 shapes++;int e[4][4]={};e[0][1]=e[1][0]=1;e[0][2]=e[2][0]=b;e[0][3]=e[3][0]=c;e[1][2]=e[2][1]=norm(q*inv(c));e[1][3]=e[3][1]=norm(q*inv(b));e[2][3]=e[3][2]=q;bool edgezero=false;for(int i=0;i<4;i++)for(int j=i+1;j<4;j++){e[i][j]=e[j][i]=norm(e[i][j]+h);if(!e[i][j])edgezero=true;}if(edgezero)continue;P es;for(int i=0;i<4;i++)for(int j=i+1;j<4;j++)es.push_back(e[i][j]);P sorted=es;std::sort(sorted.begin(),sorted.end());if(std::adjacent_find(sorted.begin(),sorted.end())!=sorted.end())continue;edgeok++;
 int beta[4]={0,norm(q-b*c),norm(q-c),norm(q-b)};int bs=norm(beta[1]+beta[2]+beta[3]);int v[4]={};for(int i=1;i<4;i++)v[i]=norm(beta[i]*(bs-2*beta[i]));
 int N=norm(b*c+b*q+c*q+q);int M=norm(b*b*c*c-b*b*c*q+b*b*c-b*b*q-b*c*c*q+b*c*c+b*q*q-b*q-c*c*q+c*q*q-c*q+q*q);int J=norm(b*c+b+c+q);int W=norm(-(long long)b*b*c*c*q+2LL*b*b*c*c-b*b*q-c*c*q+q*q*q);M=norm(q*M+h*W);int Nh=norm(N+h*J);if(!Nh||!M){chartskip++;continue;}int t=norm(-Nh*inv(M));int a[4]={1};P leads{1,mod-1};for(int i=1;i<4;i++){a[i]=norm(1+t*v[i]);leads.push_back(a[i]);leads.push_back(norm(-a[i]));}std::sort(leads.begin(),leads.end());if(leads[0]==0||std::adjacent_find(leads.begin(),leads.end())!=leads.end())continue;leadok++;
 int p=norm(-norm(h*N+q*J)*inv(Nh)-h);int k=norm(norm(q-b*b)*norm(q-c*c)*norm(q-1)*inv(M));if(!p||!k){chartskip++;continue;}bool bad=false;for(int ii=0;ii<4;ii++)for(int jj=ii+1;jj<4;jj++)if(norm(p+e[ii][jj])==0){int di=1,dj=1;for(int ll=0;ll<4;ll++)if(ll!=ii&&ll!=jj){di=norm(di*(e[ii][jj]-e[ii][ll]));dj=norm(dj*(e[ii][jj]-e[jj][ll]));}if(norm(-a[ii]*di+a[jj]*dj+k*p*(beta[ii]-beta[jj])))bad=true;}if(bad){chartskip++;continue;}
 int H[4]={},rr[4]={};for(int i=1;i<4;i++){int j=0,l=0;for(int h=1;h<4;h++)if(h!=i){if(!j)j=h;else l=h;}H[i]=norm(norm(e[0][j]*e[0][l]-a[i]*e[i][j]*e[i][l])*inv(norm(1-a[i])));rr[i]=norm(-beta[i]*inv(norm(1-a[i])));int hk=norm(norm(a[j]*e[j][0]*e[j][i]-a[l]*e[l][0]*e[l][i])*inv(norm(a[j]-a[l])));int rk=norm((beta[j]-beta[l])*inv(norm(a[j]-a[l])));if(hk!=H[i]||norm(rr[i]+rk))throw 2;}
 P gg;for(int i=1;i<4;i++){
  int j=1;while(j==i)j++;ls=norm(k*rr[i]);lh=norm(H[i]*inv(p));R V{{},{1}},Z=scalar(zz),V2=times(V,V),pz=scale(Z,p);R C0=one(),Cj=one();for(int l=0;l<4;l++){if(l!=0)C0=times(C0,plus(V2,scale(Z,e[0][l]),-1));if(l!=j)Cj=times(Cj,plus(V2,scale(Z,e[j][l]),-1));}R common=plus(V2,pz),vz=times(V,Z);R f=plus(times(plus(common,vz,-1),C0),scale(times(plus(common,vz),Cj),a[j]));R tr=times(times(scale(V,norm(k*beta[j])),plus(times(common,common),times(V2,times(Z,Z)),-1)),plus(V2,scale(Z,e[0][j]),-1));f=plus(f,tr,-1);gg=gcd(gg,f.a);gg=gcd(gg,f.b);if(gg.size()==1)break;
 }
 while(!gg.empty()&&!gg[0])gg.erase(gg.begin());if(gg.size()==1)continue;gcdpos++;gcd_rows.push_back("{\"b\":"+std::to_string(b)+",\"c\":"+std::to_string(c)+",\"q\":"+std::to_string(q)+",\"h\":"+std::to_string(h)+",\"gcd\":"+arr(gg)+"}");
 for(int z=1;z<mod;z++)if(!ev(gg,z)){
  zroots++;
  P locator{1};for(int x:es)locator=mul(locator,{norm(-z*x),0,1});
  for(int part=0;part<4;part++){int sl=part?norm(k*rr[part]):norm(-z),pc=part?norm(z*H[part]*inv(p)):norm(p*z);locator=mul(locator,{pc,sl,1});locator=mul(locator,{pc,norm(-sl),1});}
  P deriv;for(int ii=1;ii<(int)locator.size();ii++)deriv.push_back(norm(ii*locator[ii]));P collision=gcd(locator,deriv);collision_hist[collision.size()-1]++;
  if(collision.size()==1){algebraic++;algebraic_rows.push_back("{\"b\":"+std::to_string(b)+",\"c\":"+std::to_string(c)+",\"q\":"+std::to_string(q)+",\"h\":"+std::to_string(h)+",\"z\":"+std::to_string(z)+",\"locator\":"+arr(locator)+"}");}
  int sigma=root(z);if(sigma<0)continue;bad=false;for(int ee:es)if(root(ee)<0)bad=true;if(bad)continue;int tau=norm(k*inv(sigma));P C[4],A[4],B[4],F[8];for(int i=0;i<4;i++){C[i]={1};for(int j=0;j<4;j++)if(j!=i)C[i]=mul(C[i],{norm(-e[i][j]),1});A[i]=sc(C[i],a[i]);}
  P RY=add(mul({p,1},{p,1}),{0,z},-1);for(int i=1;i<4;i++){P num=add(sc(add(C[0],A[i],-1),sigma),sc(mul(RY,{norm(-e[0][i]),1}),norm(tau*beta[i])));num.resize(4);P quo(3);for(int l=3;l>=1;l--){int cc=l<(int)num.size()?num[l]:0;quo[l-1]=cc;num[l]=0;num[l-1]=norm(num[l-1]-p*cc);}if(num[0])throw 3;B[i]=quo;}
  for(int i=0;i<4;i++)for(int sg=0;sg<2;sg++){F[2*i+sg]=P(7);for(int l=0;l<4;l++)F[2*i+sg][2*l]=norm((sg?-1:1)*A[i][l]);for(int l=0;l<(int)B[i].size();l++)F[2*i+sg][2*l+1]=B[i][l];}
  P nodes,word,masks;for(int i=0;i<4;i++)for(int j=i+1;j<4;j++){int r=root(e[i][j]);if(r<1)throw 4;for(int x:{r,norm(-r)}){nodes.push_back(x);word.push_back(ev(F[2*i],x));masks.push_back((3<<(2*i))|(3<<(2*j)));}}
  bad=false;for(int part=0;part<4;part++){int sl=part?norm(tau*rr[part]):norm(-sigma),pc=part?norm(H[part]*inv(p)):p;auto rs=roots(sl,pc);if(rs.size()!=2){bad=true;break;}int mask=0;for(int i=0;i<4;i++)mask|=1<<(2*i+((part==0||i==0||i==part)?0:1));for(int x:rs)for(int sign:{1,-1}){int xx=norm(sign*x);nodes.push_back(xx);word.push_back(ev(F[sign==1?0:1],xx));masks.push_back(sign==1?mask:(mask^255));}}
  if(bad)continue;P ns=nodes;std::sort(ns.begin(),ns.end());if(ns.size()!=28||std::adjacent_find(ns.begin(),ns.end())!=ns.end())continue;split++;
  int counts[8]={};for(int j=0;j<28;j++){int mask=0;for(int i=0;i<8;i++)if(ev(F[i],nodes[j])==word[j]){mask|=1<<i;counts[i]++;}if(mask!=masks[j])throw 5;}for(int v:counts)if(v!=14)throw 6;hits++;if(!first)out<<",";first=false;out<<"{\"b\":"<<b<<",\"c\":"<<c<<",\"q\":"<<q<<",\"h\":"<<h<<",\"z\":"<<z<<",\"sigma\":"<<sigma<<",\"nodes\":"<<arr(nodes)<<",\"word\":"<<arr(word)<<",\"masks\":"<<arr(masks)<<",\"polynomials\":[";for(int i=0;i<8;i++){if(i)out<<",";out<<arr(F[i]);}out<<"]}";out.flush();
 }
}
double sec=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();out<<"],\"algebraic_candidates\":[";for(int ii=0;ii<(int)algebraic_rows.size();ii++){if(ii)out<<",";out<<algebraic_rows[ii];}out<<"],\"positive_gcds\":[";for(int ii=0;ii<(int)gcd_rows.size();ii++){if(ii)out<<",";out<<gcd_rows[ii];}out<<"],\"collision_histogram\":[";for(int ii=0;ii<29;ii++){if(ii)out<<",";out<<collision_hist[ii];}out<<"],\"counts\":{\"shapes\":"<<shapes<<",\"edge_guarded\":"<<edgeok<<",\"leading_guarded\":"<<leadok<<",\"chart_skips\":"<<chartskip<<",\"positive_gcd\":"<<gcdpos<<",\"z_roots\":"<<zroots<<",\"split_nodes\":"<<split<<",\"algebraic_distinct\":"<<algebraic<<",\"hits\":"<<hits<<"},\"seconds\":"<<sec<<",\"scope\":\"Complete prime-field search on nonzero-denominator shifted-Ceva chart with ground-field shapes; positive gcds retain extension-valued z candidates; not a characteristic-zero exclusion.\"}\n";std::cout<<"p="<<mod<<" shapes="<<shapes<<" guarded="<<leadok<<" gcdpos="<<gcdpos<<" hits="<<hits<<" seconds="<<sec<<"\n";
}
