#include <algorithm>
#include <array>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <vector>
using namespace std;using U=uint32_t;const int Q=1<<21,O=Q-1,N=128,K=8,M=129,T=29,G=384,C=1545,RR=2580;
vector<U>ex(2*O),lg(Q);U mul(U a,U b){return a&&b?ex[lg[a]+lg[b]]:0;}U inv(U a){return ex[O-lg[a]];}U pw(U a,int n){return !a?(n?0:1):ex[uint64_t(lg[a])*n%O];}
int main(){U z=1;for(int i=0;i<O;i++){ex[i]=z;lg[z]=i;z<<=1;if(z&Q)z^=Q|5;}for(int i=O;i<2*O;i++)ex[i]=ex[i-O];ifstream in("reduced_matrix.bin",ios::binary);vector<vector<U>>A(RR,vector<U>(G+1));for(auto&r:A)in.read((char*)r.data(),4*(G+1));vector<int>piv;int rank=0;for(int c=0;c<G;c++){int i=rank;while(i<RR&&!A[i][c])i++;if(i==RR)continue;swap(A[i],A[rank]);U v=inv(A[rank][c]);for(int j=c;j<G;j++)A[rank][j]=mul(A[rank][j],v);for(int ii=rank+1;ii<RR;ii++)if(A[ii][c]){v=A[ii][c];for(int j=c;j<G;j++)A[ii][j]^=mul(v,A[rank][j]);}piv.push_back(c);rank++;}vector<int>freecols;for(int c=0;c<G;c++)if(find(piv.begin(),piv.end(),c)==piv.end())freecols.push_back(c);int F=freecols.size();vector<vector<U>>bas(F,vector<U>(C));for(int k=0;k<F;k++){bas[k][freecols[k]]=1;for(int i=rank-1;i>=0;i--){U v=0;for(int j=piv[i]+1;j<G;j++)v^=mul(A[i][j],bas[k][j]);bas[k][piv[i]]=v;}}
 ifstream fix("fixture.txt");int nn,kk,mm,tt;fix>>nn>>kk>>mm>>tt;array<U,N>x,f,g;for(int i=0;i<N;i++)fix>>x[i]>>f[i]>>g[i];struct Bank{U a,b,z;array<U,K>h;array<int,T>s;};array<Bank,M>banks;for(auto&b:banks){fix>>b.a>>b.b>>b.z;for(auto&v:b.h)fix>>v;for(auto&i:b.s)fix>>i;}
 for(int bi=0;bi<M;bi++){auto&b=banks[bi];vector<vector<U>>L(T,vector<U>(K+1+F));for(int r=0;r<T;r++){int i=b.s[r];for(int j=0;j<K;j++)L[r][j]=pw(x[i],j);L[r][K]=g[i];U der=0;for(int j=1;j<K;j+=2)der^=mul(b.h[j],pw(x[i],j-1));for(int t=0;t<F;t++)L[r][K+1+t]=mul(der,bas[t][i])^bas[t][N+i]^mul(b.z,bas[t][2*N+i]);}int rr=0;for(int c=0;c<K+1;c++){int r=rr;while(r<T&&!L[r][c])r++;if(r==T)return 2;swap(L[r],L[rr]);U v=inv(L[rr][c]);for(int j=c;j<K+1+F;j++)L[rr][j]=mul(L[rr][j],v);for(int i=0;i<T;i++)if(i!=rr&&L[i][c]){v=L[i][c];for(int j=c;j<K+1+F;j++)L[i][j]^=mul(v,L[rr][j]);}rr++;}for(int r=K+1;r<T;r++)for(int t=0;t<F;t++)if(L[r][K+1+t])return 3;for(int t=0;t<F;t++)for(int j=0;j<K+1;j++)bas[t][G+bi*(K+1)+j]=L[j][K+1+t];}
 ifstream cert("contradiction.bin",ios::binary);vector<U>w(M*T);cert.read((char*)w.data(),4*w.size());vector<vector<U>>quad(F,vector<U>(F));for(int bi=0;bi<M;bi++){auto&b=banks[bi];for(int r=0;r<T;r++){U wt=w[bi*T+r];if(!wt)continue;int i=b.s[r],off=G+bi*(K+1);U h2=0;for(int j=2;j<K;j++)if((j*(j-1)/2)&1)h2^=mul(b.h[j],pw(x[i],j-2));vector<U>dv(F);for(int t=0;t<F;t++)for(int j=1;j<K;j+=2)dv[t]^=mul(bas[t][off+j],pw(x[i],j-1));for(int t=0;t<F;t++){U a=bas[t][i],c=bas[t][off+K],d=bas[t][2*N+i];quad[t][t]^=mul(wt,mul(h2,mul(a,a))^mul(a,dv[t])^mul(c,d));for(int u=t+1;u<F;u++)quad[t][u]^=mul(wt,mul(a,dv[u])^mul(bas[u][i],dv[t])^mul(c,bas[u][2*N+i])^mul(bas[u][off+K],d));}}}
 ofstream bo("tangent_basis.bin",ios::binary);for(auto&v:bas)bo.write((char*)v.data(),4*C);ofstream qo("restricted_quadratic.bin",ios::binary);int nz=0;for(int t=0;t<F;t++)for(int u=t;u<F;u++){qo.write((char*)&quad[t][u],4);nz+=quad[t][u]!=0;}cout<<"{\"global_jacobian_rank\":"<<rank<<",\"full_jacobian_rank\":"<<rank+M*(K+1)<<",\"tangent_dimension\":"<<F<<",\"quadratic_coefficients\":"<<F*(F+1)/2<<",\"nonzero_quadratic_coefficients\":"<<nz<<",\"selected_certificate_obstructs_ramification_two\":"<<(nz?"false":"true")<<"}\n";}
