#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <random>
#include <vector>
using namespace std;using U=uint32_t;using Q=uint64_t;
const int D=21,SZ=1<<D,O=SZ-1,N=128,K=8,M=129,T=29,G=384;
vector<U> ex(2*O),lg(SZ);U mul(U a,U b){return a&&b?ex[lg[a]+lg[b]]:0;}U inv(U a){return ex[O-lg[a]];}U pw(U a,int n){return !a?(n?0:1):ex[uint64_t(lg[a])*n%O];}
struct R{Q l,h;};R add(R a,R b){return {a.l^b.l,a.h^b.h^(a.l&b.l)};}R neg(R a){return {a.l,a.h^a.l};}R lift(U a){return {a,0};}
R rmul(R a,R b){R r{0,0};for(int i=0;i<D;i++){if(a.l>>i&1)r=add(r,{b.l<<i,b.h<<i});if(a.h>>i&1)r.h^=b.l<<i;}for(int j=2*D-2;j>=D;j--){int v=(r.l>>j&1)+2*(r.h>>j&1);Q mask=(Q(1)<<j)|(Q(1)<<(j-D+2))|(Q(1)<<(j-D));if(v==1)r=add(r,{mask,mask});if(v==2)r.h^=mask;if(v==3)r=add(r,{mask,0});}return r;}
struct Rec{int a,b;U z;array<U,K> h;vector<int>s;};
int main(){auto st=chrono::steady_clock::now();U cur=1;for(int i=0;i<O;i++){if(i&&cur==1)return 2;ex[i]=cur;lg[cur]=i;cur<<=1;if(cur&SZ)cur^=SZ|5;}if(cur!=1)return 3;for(int i=O;i<2*O;i++)ex[i]=ex[i-O];U th=2,shift=mul(th,th),gen=ex[O/127];array<U,7>bas{};bas[0]=1;for(int i=1;i<7;i++)bas[i]=mul(bas[i-1],gen);array<U,N>x{},f{},g{};for(int i=0;i<N;i++){for(int j=0;j<7;j++)if(i>>j&1)x[i]^=bas[j];g[i]=pw(x[i],15);f[i]=pw(x[i],63)^mul(th,pw(x[i],31))^mul(shift,g[i]);}
 vector<pair<int,int>> ps;for(int a=1;a<N;a++)for(int b=a+1;b<N;b++)if(b<(a^b))ps.push_back({a,b});if(ps.size()!=2667)return 4;mt19937 rng(20260918);shuffle(ps.begin(),ps.end(),rng);vector<Rec>rs;
 for(int s=0;s<M;s++){auto[a,b]=ps[s];vector<U>L{1};vector<int>S;for(int i=0;i<N;i++)if(!(__builtin_parity(i&a)||__builtin_parity(i&b))){vector<U>v(L.size()+1);for(int j=0;j<(int)L.size();j++){v[j]^=mul(x[i],L[j]);v[j+1]^=L[j];}L=v;if(i)S.push_back(i);}if(L.size()!=33||S.size()!=31)return 5;U aa=L[16],bb=L[8],cc=mul(aa,aa)^th;Rec r{a,b,pw(aa,3)^mul(bb,bb)^mul(th,aa)^shift,{},S};vector<U>v(9);for(int j=1;j<=8;j++)v[j]^=mul(cc,L[j]);for(int j=1;j<=4;j++)v[2*j]^=mul(L[j],L[j]);for(int j=1;j<=8;j++)r.h[j-1]=v[j];for(int i=0;i<N;i++){U hv=0;for(int j=K-1;j>=0;j--)hv=mul(hv,x[i])^r.h[j];if((hv==(f[i]^mul(r.z,g[i])))!=(i&&!(__builtin_parity(i&a)||__builtin_parity(i&b))))return 6;}shuffle(r.s.begin(),r.s.end(),rng);r.s.resize(T);sort(r.s.begin(),r.s.end());for(auto&o:rs)if(o.z==r.z)return 7;rs.push_back(r);}
 for(int i=0;i<1000;i++){U a=rng()%SZ,b=rng()%SZ;auto c=rmul(lift(a),lift(b));if(c.l!=mul(a,b)||c.h>=SZ)return 8;}
 ofstream lp("local_relations.bin",ios::binary); vector<vector<U>>mat;int bankindex=0;for(auto&r:rs){vector<vector<U>>rows;for(int idx:r.s){vector<U>row(K+1+G+1+T);row[K+1+G+1+rows.size()]=1;U xp=1;for(int j=0;j<K;j++){row[j]=xp;xp=mul(xp,x[idx]);}row[K]=g[idx];U der=0;for(int j=1;j<K;j+=2)der^=mul(r.h[j],pw(x[idx],j-1));row[K+1+idx]=der;row[K+1+N+idx]=1;row[K+1+2*N+idx]=r.z;R val{0,0};for(int j=K-1;j>=0;j--)val=add(rmul(val,lift(x[idx])),lift(r.h[j]));val=add(val,neg(lift(f[idx])));val=add(val,neg(rmul(lift(r.z),lift(g[idx]))));if(val.l||val.h>=SZ)return 9;row[K+1+G]=val.h;rows.push_back(move(row));}int rank=0;for(int c=0;c<K+1;c++){int z=rank;while(z<T&&!rows[z][c])z++;if(z==T)continue;swap(rows[z],rows[rank]);U fac=inv(rows[rank][c]);for(int j=c;j<(int)rows[rank].size();j++)rows[rank][j]=mul(rows[rank][j],fac);for(int i=0;i<T;i++)if(i!=rank&&rows[i][c]){fac=rows[i][c];for(int j=c;j<(int)rows[i].size();j++)rows[i][j]^=mul(fac,rows[rank][j]);}rank++;}if(rank!=K+1)return 10;for(int i=rank;i<T;i++){mat.emplace_back(rows[i].begin()+K+1,rows[i].begin()+K+1+G+1);U bi=bankindex;lp.write((char*)&bi,4);lp.write((char*)&rows[i][K+1+G+1],4*T);}bankindex++;}lp.close();ofstream raw("reduced_matrix.bin",ios::binary);for(auto&row:mat)raw.write((char*)row.data(),4*(G+1));raw.close();
 int rank=0;for(int c=0;c<G;c++){int z=rank;while(z<(int)mat.size()&&!mat[z][c])z++;if(z==(int)mat.size())continue;swap(mat[z],mat[rank]);U fac=inv(mat[rank][c]);for(int j=c;j<=G;j++)mat[rank][j]=mul(mat[rank][j],fac);for(int i=rank+1;i<(int)mat.size();i++)if(mat[i][c]){fac=mat[i][c];mat[i][c]=0;for(int j=c+1;j<=G;j++)mat[i][j]^=mul(fac,mat[rank][j]);}rank++;}int bad=0;for(int i=rank;i<(int)mat.size();i++){for(int c=0;c<G;c++)if(mat[i][c])return 11;if(mat[i][G])bad++;}
 ofstream o("fixture.txt");o<<N<<" "<<K<<" "<<M<<" "<<T<<"\n";for(int i=0;i<N;i++)o<<x[i]<<" "<<f[i]<<" "<<g[i]<<"\n";for(auto&r:rs){o<<r.a<<" "<<r.b<<" "<<r.z;for(auto v:r.h)o<<" "<<v;for(int i:r.s)o<<" "<<i;o<<"\n";}o.close();double sec=chrono::duration<double>(chrono::steady_clock::now()-st).count();cout<<"{\"field_degree\":21,\"modulus\":2097157,\"N\":128,\"K\":8,\"M\":129,\"T\":29,\"reduced_equations\":"<<mat.size()<<",\"global_variables\":384,\"coefficient_rank\":"<<rank<<",\"augmented_rank\":"<<rank+(bad>0)<<",\"inconsistent_rows\":"<<bad<<",\"first_lift_exists\":"<<(bad?"false":"true")<<",\"seconds\":"<<sec<<"}\n";
}
